name: Authenticate to Google Cloud

description: Authenticate to Google Cloud using Workload Identity Federation

inputs:
  GCP_PROJECT:
    description: Google Cloud Project ID
    required: true

  WORKLOAD_IDENTITY_PROVIDER:
    description: Google Cloud Workload Identity Provider
    required: true

  SERVICE_ACCOUNT:
    description: Google Cloud service account to impersonate
    required: true

runs:
  using: composite

  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        project_id: ${{ inputs.GCP_PROJECT }}
        workload_identity_provider: ${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ inputs.SERVICE_ACCOUNT }}