name: Ansible Playbooks

on:
  workflow_call:
    inputs:
      CLOUD_PROVIDER:
        required: true
        type: string
  
      ENVIRONMENT:
        required: true
        type: string

      PLAYBOOK:
        required: true
        type: string

      ANSIBLE_COMMAND:
        required: true
        type: string

      ANSIBLE_EXTRA_ARGS:
        required: false
        type: string
        default: ""
      
      ANSIBLE_VARS_FILE:
        required: false
        type: string
        default: ""

env:
  INVENTORY_DIR: ./inventories
  PLAYBOOK_DIR: ./playbooks
  ANSIBLE_LINT_CONFIG_PATH: ./.ansible-lint.yaml
  ANSIBLE_PYTHON_VENV: /opt/ansible-venv

jobs:
  validate:
    runs-on: robot-shop-runner-azure-dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Cloud Credentials
      uses: robot-shop-DevOps/robot-shop-github-actions/.github/actions/setup-cloud-creds@main
      with:
        CLOUD_PROVIDER: ${{ inputs.CLOUD_PROVIDER }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        APP_SERVICE: ansible

    - name: Setup Ansible venv
      run: |
        if [[ ! -d "${{ env.ANSIBLE_PYTHON_VENV }}" ]]; then
          echo "Creating ansible venv..."
          sudo python3 -m venv ${{ env.ANSIBLE_PYTHON_VENV }}
          sudo ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install "ansible[azure]" ansible-lint
        else
          echo "Ansible venv already exists, skipping creation."
        fi

    - name: Install dependencies
      run: |
        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.txt'

        if [[ -f "$file_path" ]]; then
          echo "Installing python dependencies from $file_path"
          sudo ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install -r "$file_path"
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Install Ansible Galaxy dependencies
      run: |
        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.yaml'

        if [[ -f "$file_path" ]]; then
          echo "Installing ansible galaxy dependencies from $file_path"
          sudo ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-galaxy collection install -r "$file_path" -p ./collections
          sudo ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-galaxy role install -r "$file_path" -p ./roles
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Lint ansible playbooks
      run: |
        set -e
        ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-lint -c ${{ env.ANSIBLE_LINT_CONFIG_PATH }} ${{ env.PLAYBOOK_DIR }}

  dry-run-playbooks:
    needs: validate
    runs-on: robot-shop-runner-azure-dev
    if: ${{ inputs.ANSIBLE_COMMAND == 'dry_run'}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Cloud Credentials
      uses: robot-shop-DevOps/robot-shop-github-actions/.github/actions/setup-cloud-creds@main
      with:
        CLOUD_PROVIDER: ${{ inputs.CLOUD_PROVIDER }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        APP_SERVICE: ansible

    - name: Dry run ansible playbooks
      run: |
        echo "Dry Running playbook ${{ inputs.PLAYBOOK }}"
        
        VARS_OPTION=""
        if [[ -n "${{ inputs.ANSIBLE_VARS_FILE }}" ]]; then
          VARS_OPTION="-e @${{ inputs.ANSIBLE_VARS_FILE }}"
        fi

        ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-playbook -i ${{ env.INVENTORY_DIR }}/${{ inputs.ENVIRONMENT }}/hosts.yaml \
        ${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/${{ inputs.PLAYBOOK }}.yaml \
        ${{ inputs.ANSIBLE_EXTRA_ARGS }} \
        $VARS_OPTION \
        --check --diff
        
  run-playbooks:
    needs: validate
    runs-on: robot-shop-runner-azure-dev
    if: ${{ github.ref_name == 'develop' && inputs.ANSIBLE_COMMAND == 'run' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Cloud Credentials
      uses: robot-shop-DevOps/robot-shop-github-actions/.github/actions/setup-cloud-creds@main
      with:
        CLOUD_PROVIDER: ${{ inputs.CLOUD_PROVIDER }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        APP_SERVICE: ansible

    - name: Setup Ansible venv
      run: |
        if [[ ! -d "${{ env.ANSIBLE_PYTHON_VENV }}" ]]; then
          echo "Creating ansible venv..."
          sudo python3 -m venv ${{ env.ANSIBLE_PYTHON_VENV }}
          sudo ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install "ansible[azure]" ansible-lint
        else
          echo "Ansible venv already exists, skipping creation."
        fi

    - name: Install dependencies
      run: |
        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.txt'

        if [[ -f "$file_path" ]]; then
          echo "Installing python dependencies from $file_path"
          sudo ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install -r "$file_path"
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Install Ansible Galaxy dependencies
      run: |
        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.yaml'

        if [[ -f "$file_path" ]]; then
          echo "Installing ansible galaxy dependencies from $file_path"
          sudo ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-galaxy collection install -r "$file_path" -p ./collections
          sudo ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-galaxy role install -r "$file_path" -p ./roles
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Run playbooks
      run: |
        echo "Running playbook ${{ inputs.PLAYBOOK }}"
        
        VARS_OPTION=""
        if [[ -n "${{ inputs.ANSIBLE_VARS_FILE }}" ]]; then
          VARS_OPTION="-e @${{ inputs.ANSIBLE_VARS_FILE }}"
        fi

        ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-playbook -i ${{ env.INVENTORY_DIR }}/${{ inputs.ENVIRONMENT }}/hosts.yaml \
        ${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/${{ inputs.PLAYBOOK }}.yaml \
        ${{ inputs.ANSIBLE_EXTRA_ARGS }} \
        $VARS_OPTION \