name: Ansible Playbooks

on:
  workflow_call:
    inputs:
      CLOUD_PROVIDER:
        required: true
        type: string
  
      ENVIRONMENT:
        required: true
        type: string

      PLAYBOOK:
        required: true
        type: string

      ANSIBLE_COMMAND:
        required: true
        type: string

      ANSIBLE_EXTRA_ARGS:
        required: false
        type: string
        default: ""
      
      ANSIBLE_VARS_FILE:
        required: false
        type: string
        default: ""

env:
  INVENTORY_DIR: ./inventories
  PLAYBOOK_DIR: ./playbooks
  ANSIBLE_LINT_CONFIG_PATH: ./.ansible-lint.yaml
  ANSIBLE_PYTHON_VENV: /home/GitHubActions/ansible-venv

jobs:
  validate:
    runs-on: robot-shop-runner-azure-dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Ansible venv
      run: |
        if [[ ! -d "${{ env.ANSIBLE_PYTHON_VENV }}" ]]; then
          echo "Creating ansible venv..."
           python3 -m venv ${{ env.ANSIBLE_PYTHON_VENV }}
           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install "ansible[azure]" ansible-lint
        else
          echo "Ansible venv already exists, skipping creation."
        fi

    - name: Install Ansible Galaxy dependencies
      run: |
        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.yaml'

        if [[ -f "$file_path" ]]; then
          echo "Installing ansible galaxy dependencies from $file_path"
           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-galaxy collection install -r "$file_path" -p ./collections --force
           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-galaxy role install -r "$file_path" -p ./roles

           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install -r ./collections/ansible_collections/azure/azcollection/requirements.txt
        else
          echo "No $file_path file found, skipping."
        fi

        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.txt'

        if [[ -f "$file_path" ]]; then
          echo "Installing python dependencies from $file_path"
           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install -r "$file_path"
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Lint ansible playbooks
      run: |
        set -e
        ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-lint -c ${{ env.ANSIBLE_LINT_CONFIG_PATH }} ${{ env.PLAYBOOK_DIR }}

  playbooks:
    needs: validate
    runs-on: robot-shop-runner-azure-dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set Azure credentials
      run: |
        echo "AZURE_CLIENT_ID=${{ secrets.ROBOT_SHOP_DEV_AZURE_CLIENT_ID_ANSIBLE }}" >> $GITHUB_ENV
        echo "AZURE_SECRET=${{ secrets.ROBOT_SHOP_DEV_AZURE_CLIENT_SECRET_ANSIBLE }}" >> $GITHUB_ENV
        echo "AZURE_TENANT=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ secrets.ROBOT_SHOP_DEV_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

    - name: Setup Ansible venv
      run: |
        if [[ ! -d "${{ env.ANSIBLE_PYTHON_VENV }}" ]]; then
          echo "Creating ansible venv..."
           python3 -m venv ${{ env.ANSIBLE_PYTHON_VENV }}
           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install "ansible[azure]" ansible-lint
        else
          echo "Ansible venv already exists, skipping creation."
        fi

    - name: Install Ansible Galaxy dependencies
      run: |
        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.yaml'

        if [[ -f "$file_path" ]]; then
          echo "Installing ansible galaxy dependencies from $file_path"
           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-galaxy collection install -r "$file_path" -p ./collections --force
           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-galaxy role install -r "$file_path" -p ./roles

           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install -r ./collections/ansible_collections/azure/azcollection/requirements.txt
        else
          echo "No $file_path file found, skipping."
        fi

        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.txt'

        if [[ -f "$file_path" ]]; then
          echo "Installing python dependencies from $file_path"
           ${{ env.ANSIBLE_PYTHON_VENV }}/bin/pip install -r "$file_path"
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Dry run ansible playbooks
      if: ${{ inputs.ANSIBLE_COMMAND == 'dry_run'}}
      run: |
        echo "Dry Running playbook ${{ inputs.PLAYBOOK }}"
        
        VARS_OPTION=""
        if [[ -n "${{ inputs.ANSIBLE_VARS_FILE }}" ]]; then
          VARS_OPTION="-e @${{ inputs.ANSIBLE_VARS_FILE }}"
        fi

        ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-playbook -i ${{ env.INVENTORY_DIR }}/${{ inputs.ENVIRONMENT }}/hosts.yaml \
        ${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/${{ inputs.PLAYBOOK }}.yaml \
        ${{ inputs.ANSIBLE_EXTRA_ARGS }} \
        $VARS_OPTION \
        --check --diff

    - name: Run playbooks
      if: ${{ github.ref_name == 'develop' && inputs.ANSIBLE_COMMAND == 'run' }}
      run: |
        echo "Running playbook ${{ inputs.PLAYBOOK }}"
        
        VARS_OPTION=""
        if [[ -n "${{ inputs.ANSIBLE_VARS_FILE }}" ]]; then
          VARS_OPTION="-e @${{ inputs.ANSIBLE_VARS_FILE }}"
        fi

        ${{ env.ANSIBLE_PYTHON_VENV }}/bin/ansible-playbook -i ${{ env.INVENTORY_DIR }}/${{ inputs.ENVIRONMENT }}/hosts.yaml \
        ${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/${{ inputs.PLAYBOOK }}.yaml \
        ${{ inputs.ANSIBLE_EXTRA_ARGS }} \
        $VARS_OPTION   