name: Ansible Playbooks

on:
  workflow_call:
    inputs:
      CLOUD_PROVIDER:
        required: true
        type: string
  
      ENVIRONMENT:
        required: true
        type: string

      PLAYBOOK:
        required: true
        type: string

      ANSIBLE_COMMAND:
        required: true
        type: string

      ANSIBLE_EXTRA_ARGS:
        required: false
        type: string
        default: ""
      
      ANSIBLE_VARS_FILE:
        required: false
        type: string
        default: ""

env:
  INVENTORY_DIR: ./inventories
  PLAYBOOK_DIR: ./playbooks
  ANSIBLE_LINT_CONFIG_PATH: ./.ansible-lint.yaml

jobs:
  validate:
    runs-on: robot-shop-runner-azure-dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Cloud Credentials
      uses: robot-shop-DevOps/robot-shop-github-actions/.github/actions/setup-cloud-creds@main
      with:
        CLOUD_PROVIDER: ${{ inputs.CLOUD_PROVIDER }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        APP_SERVICE: ansible

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        
        $(which python3) -m pip install --upgrade pip --break-system-packages
        $(which python3) -m pip install "ansible[azure]" ansible-lint --break-system-packages

        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.txt'

        if [[ -f "$file_path" ]]; then
          echo "Installing python dependencies from $file_path"
          $(which python3) -m pip install -r "$file_path" --break-system-packages
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Install Ansible Galaxy dependencies
      run: |
        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.yaml'

        if [[ -f "$file_path" ]]; then
          echo "Installing ansible galaxy dependencies from $file_path"
          ansible-galaxy collection install -r "$file_path" -p ./collections
          ansible-galaxy role install -r "$file_path" -p ./roles
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Lint ansible playbooks
      run: |
        set -e
        ansible-lint -c ${{ env.ANSIBLE_LINT_CONFIG_PATH }} ${{ env.PLAYBOOK_DIR }}

  dry-run-playbooks:
    needs: validate
    runs-on: robot-shop-runner-azure-dev
    if: ${{ inputs.ANSIBLE_COMMAND == 'dry_run'}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Cloud Credentials
      uses: robot-shop-DevOps/robot-shop-github-actions/.github/actions/setup-cloud-creds@main
      with:
        CLOUD_PROVIDER: ${{ inputs.CLOUD_PROVIDER }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        APP_SERVICE: ansible

    - name: Dry run ansible playbooks
      run: |
        echo "Dry Running playbook ${{ inputs.PLAYBOOK }}"
        
        VARS_OPTION=""
        if [[ -n "${{ inputs.ANSIBLE_VARS_FILE }}" ]]; then
          VARS_OPTION="-e @${{ inputs.ANSIBLE_VARS_FILE }}"
        fi

        ansible-playbook -i ${{ env.INVENTORY_DIR }}/${{ inputs.ENVIRONMENT }}/hosts.yaml \
        ${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/${{ inputs.PLAYBOOK }}.yaml \
        ${{ inputs.ANSIBLE_EXTRA_ARGS }} \
        $VARS_OPTION \
        --check --diff
        
  run-playbooks:
    needs: validate
    runs-on: robot-shop-runner-azure-dev
    if: ${{ github.ref_name == 'develop' && inputs.ANSIBLE_COMMAND == 'run' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Cloud Credentials
      uses: robot-shop-DevOps/robot-shop-github-actions/.github/actions/setup-cloud-creds@main
      with:
        CLOUD_PROVIDER: ${{ inputs.CLOUD_PROVIDER }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        APP_SERVICE: ansible

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        
        $(which python3) -m pip install --upgrade pip --break-system-packages
        $(which python3) -m pip install "ansible[azure]" ansible-lint --break-system-packages

        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.txt'

        if [[ -f "$file_path" ]]; then
          echo "Installing python dependencies from $file_path"
          $(which python3) -m pip install -r "$file_path" --break-system-packages
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Install Ansible Galaxy dependencies
      run: |
        file_path='${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/requirements.yaml'

        if [[ -f "$file_path" ]]; then
          echo "Installing ansible galaxy dependencies from $file_path"
          ansible-galaxy collection install -r "$file_path" -p ./collections
          ansible-galaxy role install -r "$file_path" -p ./roles
        else
          echo "No $file_path file found, skipping."
        fi

    - name: Debug Python environment
      run: |
        echo "Python path:"
        which $(which python3)

        echo "Python version:"
        $(which python3) --version

        echo "Installed Azure libraries:"
        $(which python3) -m pip list | grep -E "azure|msrest"

    - name: Debug ansible python
      run: |
        echo "ansible shebang: $(head -1 $(which ansible-playbook))"
        echo "ansible-playbook path: $(which ansible-playbook)"

    - name: Run playbooks
      run: |
        echo "Running playbook ${{ inputs.PLAYBOOK }}"
        
        VARS_OPTION=""
        if [[ -n "${{ inputs.ANSIBLE_VARS_FILE }}" ]]; then
          VARS_OPTION="-e @${{ inputs.ANSIBLE_VARS_FILE }}"
        fi

        ansible-playbook -i ${{ env.INVENTORY_DIR }}/${{ inputs.ENVIRONMENT }}/hosts.yaml \
        ${{ env.PLAYBOOK_DIR }}/${{ inputs.PLAYBOOK }}/${{ inputs.PLAYBOOK }}.yaml \
        ${{ inputs.ANSIBLE_EXTRA_ARGS }} \
        $VARS_OPTION \