name: Databases

on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string

      NAMESPACE:
        required: true
        type: string

      RELEASE:
        required: true
        type: string

      DOCKERFILE_PATH:
        required: true
        type: string

      IMAGE_OVERRIDE_PATHS:
        required: true
        type: string

env:
  REGISTRY_NAME: robotshopdevacr
  REGISTRY_URL: robotshopdevacr.azurecr.io

jobs:
  build:
    runs-on: robot-shop-runner-azure-dev
    outputs:
      IMAGE_TAG: ${{ steps.version.outputs.IMAGE_TAG }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Get latest image tag
      id: version
      run: |
        branch_name=$(echo "$GITHUB_REF_NAME" | tr '/' '-')
        image_tag="$branch_name-${GITHUB_SHA::8}"
        echo "IMAGE_TAG=$image_tag" >> $GITHUB_OUTPUT

    - name: Setup Cloud Credentials
      uses: ./.github/actions/setup-cloud-creds
      with:
        CLOUD_PROVIDER: azure
        ENVIRONMENT: dev
        APP_SERVICE: acr

    - name: Login to ACR with buildah
      uses: ./.github/actions/acr-buildah-login
      with:
        REGISTRY_URL: ${{ env.REGISTRY_URL }}
        REGISTRY_NAME: ${{ env.REGISTRY_NAME }}

    - name: Build image with Buildah
      run: |
        buildah build -t ${{ inputs.IMAGE }} ${{ inputs.DOCKERFILE_PATH }}
        buildah tag ${{ inputs.IMAGE }} ${{ env.REGISTRY_URL }}/robot-shop/${{ inputs.IMAGE }}:${{ steps.version.outputs.IMAGE_TAG }}

    - name: Push image with Buildah
      run: |
        buildah push ${{ env.REGISTRY_URL }}/robot-shop/${{ inputs.IMAGE }}:${{ steps.version.outputs.IMAGE_TAG }}

  deploy:
    if: ${{ github.ref_name == 'develop' }}
    needs: build
    runs-on: robot-shop-runner-azure-dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: 3.9.0

    - name: Prepare helm deployment
      uses: ./.github/actions/prepare-helm-deploy
      with:
        NAMESPACE: ${{ inputs.NAMESPACE }}

    - name: Deploy helm chart
      uses: ./.github/actions/helm-deploy
      with:
        RELEASE: ${{ inputs.RELEASE }}
        NAMESPACE: ${{ inputs.NAMESPACE }}
        CHART_PATH: ${{ env.chart_path }}
        IMAGE: ${{ inputs.IMAGE }}:${{ needs.build.outputs.IMAGE_TAG }}
        WORKLOAD_TYPE: statefulset
        IMAGE_OVERRIDE_PATHS: ${{ inputs.IMAGE_OVERRIDE_PATHS }}