name: Python Microservices

on:
  workflow_call:
    inputs:
      MICROSERVICE:
        required: true
        type: string

      IMAGE:
        required: true
        type: string

      NAMESPACE:
        required: true
        type: string

      RELEASE:
        required: true
        type: string

      WORKING_DIR:
        required: true
        type: string

      DOCKERFILE_PATH:
        required: true
        type: string


env:
  REGISTRY_NAME: robotshopdevacr
  REGISTRY_URL: robotshopdevacr.azurecr.io


jobs:
  test:
    runs-on: robot-shop-runner-azure-dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create virtual environment
      run: python -m venv venv

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r ${{ inputs.WORKING_DIR }}/requirements.txt

    - name: Run unit tests
      working-directory: ${{ inputs.WORKING_DIR }}
      run: |
        source ../venv/bin/activate
        mkdir -p test-results
        pytest -v --junitxml=test-results/junit.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.MICROSERVICE }}-test-results
        path: ${{ inputs.WORKING_DIR }}/test-results

  build:
    runs-on: robot-shop-runner-azure-dev
    needs: test
    outputs:
      IMAGE_TAG: ${{ steps.image.outputs.IMAGE_TAG }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Setup Cloud Credentials
      uses: ./.github/actions/setup-cloud-creds
      with:
        CLOUD_PROVIDER: azure
        ENVIRONMENT: dev
        APP_SERVICE: acr

    - name: Login to ACR with buildah
      uses: ./.github/actions/acr-buildah-login
      with:
        REGISTRY_URL: ${{ env.REGISTRY_URL }}
        REGISTRY_NAME: ${{ env.REGISTRY_NAME }}

    - name: Build & Push image with buildah
      id: image
      uses: ./.github/actions/buildah-build-push
      with:
        IMAGE: ${{ inputs.IMAGE }}
        DOCKERFILE_PATH: ${{ inputs.DOCKERFILE_PATH }}
        REGISTRY_URL: ${{ env.REGISTRY_URL }}

  deploy:
    if: ${{ github.ref_name == 'develop' }}
    needs: build
    runs-on: robot-shop-runner-azure-dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: 3.9.0

    - name: Prepare helm deployment
      uses: ./.github/actions/prepare-helm-deploy
      with:
        NAMESPACE: ${{ inputs.NAMESPACE }}

    - name: Deploy helm chart
      uses: ./.github/actions/helm-deploy
      with:
        RELEASE: ${{ inputs.RELEASE }}
        NAMESPACE: ${{ inputs.NAMESPACE }}
        CHART_PATH: ${{ env.chart_path }}
        IMAGE: ${{ inputs.IMAGE }}:${{ needs.build.outputs.IMAGE_TAG }}
        WORKLOAD_TYPE: deployment