name: Shell Scripts

on:
  workflow_call:
    inputs:
      CLOUD_PROVIDER:
        required: true
        type: string

      ENVIRONMENT:
        required: true
        type: string

      SCRIPT_PATH:
        required: true
        type: string

      EXTRA_ENV_VARS:
        required: false
        type: string
        description: "env vars the script expects. Pass name=value. Use | for seperation of multiple pairs"

jobs:
  shell_script:
    runs-on: robot-shop-runner-azure-dev
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Setup Cloud Credentials
      uses: robot-shop-DevOps/robot-shop-github-actions/.github/actions/setup-cloud-creds@main
      with:
        CLOUD_PROVIDER: ${{ inputs.CLOUD_PROVIDER }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        APP_SERVICE: automation

    - name: Export extra environment variables
      if: ${{ inputs.EXTRA_ENV_VARS != '' }}
      run: |
        set -e
        IFS='|'

        read -r var <<< ${{ inputs.EXTRA_ENV_VARS }}
          for v in "${var[@]}"; do
              echo "$v" >> $GITHUB_ENV
          done

    - name: Run shell script
      if: ${{ github.ref_name == 'develop' }}
      run: |
        set -e
        chmod 700 ${{ inputs.SCRIPT_PATH }}
        ${{ inputs.SCRIPT_PATH }}